# Amazon Bedrock AgentCore Configuration
# Generated for game-recommendation-agent

default_agent: game-guide

agents:
  game-guide:
    name: game-guide
    description: "Game recommendation agent powered by Metacritic and The Game Awards data"
    entrypoint: main.py
    runtime:
      python_version: "3.12"
